# version: "3"
# services:
#   elastic_search:
#     image: elasticsearch:8.9.2
#     container_name: kumo_elastic
#     ports:
#       - 9200:9200
#       - 9300:9300
#     environment:
#       - discovery.type=single-node
#       - xpack.security.enabled=false
#   kibana:
#     depends_on:
#       - elastic_search
#     image: kibana:8.9.2
#     container_name: kumo_kibana
#     ports:
#       - 5601:5601
#     environment:
#       - ELASTICSEARCH_HOSTS=http://kumo_elastic:9200


#https://viblo.asia/p/tich-hop-elasticsearch-va-kibana-vao-docker-compose-Az45bymqlxY

version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge
